version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
